package controllers

import (
	"github.com/redneckbeard/gadget"
	"{{.Project}}/app"
)

func init() {
	app.Register(&{{.Name}}Controller{})
}

type {{.Name}}Controller struct {
	*gadget.DefaultController
}
{{if matchString .Name "Home"}}
func (c *HomeController) Plural() string { return "home" }

func (c *HomeController) Index(r *gadget.Request) (int, interface{})   { 
	// Welcome to Gadget. Your first controller method starts here.
	return 404, "Index method generated by the gdgt tool." 
}
{{end}}
{{if .Stubs}}
func (c *{{.Name}}Controller) Index(r *gadget.Request) (int, interface{})   { return 404, "Index method generated by the gdgt tool." }
func (c *{{.Name}}Controller) Show(r *gadget.Request) (int, interface{})    { return 404, "Show method generated by the gdgt tool." }
func (c *{{.Name}}Controller) Create(r *gadget.Request) (int, interface{})  { return 404, "Create method generated by the gdgt tool." }
func (c *{{.Name}}Controller) Update(r *gadget.Request) (int, interface{})  { return 404, "Update method generated by the gdgt tool." }
func (c *{{.Name}}Controller) Destroy(r *gadget.Request) (int, interface{}) { return 404, "Destroy method generated by the gdgt tool." }
{{end}}
